name: Deploy to Railway Prod Environment

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - name: Install packages
        run: npm install
      - name: Create database
        run: npx sequelize db:create
        env:
          DB_HOST: localhost
          DB_NAME: ci-cd
          DB_USERNAME: postgres
          DB_PASSWORD: password
          ENVIRONMENT: test
          SENTRY_DSN: https://2247454ec18e40f9ac09e7dd2651b6fd@o4505210782547968.ingest.sentry.io/4505210803126273
      - name: Migrate database
        run: npx sequelize db:migrate
        env:
          DB_HOST: localhost
          DB_NAME: ci-cd
          DB_USERNAME: postgres
          DB_PASSWORD: password
          ENVIRONMENT: test
          SENTRY_DSN: https://2247454ec18e40f9ac09e7dd2651b6fd@o4505210782547968.ingest.sentry.io/4505210803126273
      - name: Run test
        run: npm test
        env:
          DB_HOST: localhost
          DB_NAME: ci-cd
          DB_USERNAME: postgres
          DB_PASSWORD: password
          JWT_SECRET_KEY: rahasia
          ENVIRONMENT: test
          SENTRY_DSN: https://2247454ec18e40f9ac09e7dd2651b6fd@o4505210782547968.ingest.sentry.io/4505210803126273

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - name: Install packages
        run: npm install
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}